### ISSUE TITLE
Copyright Violation

### ISSUE THREAD

**Issue by jacoblambda** [Code-Bullet/Jump-King#3]
Preface: I'm not associated with the dev team or anyone. I'm just a random person and fan of your channel who happens to know how touchy copyright law can be.

As it stands, this repository is hosting what are essentially ripped assets from the original Jump King game (and as much is even said in the video regarding the creation of this repo). To avoid the risk of getting a copyright strike from the official developers on the repo, I'd recommend one of the following:

1. Getting written permission from the developers to host their assets and posting it in the repository.
2. Removing the assets from the repository and providing a mechanism for users to grab the assets from an official copy of the game and load them into the hosted page. This would also require you to rebase the repo to remove the assets from git's history.
3. Worst case you may have to take down the repository all together if it's seen as non-kosher by the official devs however as this is an interesting and fun project I'd hope it wouldn't come to that.

**Comment by Daniele122898** [comment]
This is ignoring the fact that he essentially made a 1 to 1 copy of the game, down to even the same jump mechanics, using all the assets of the game and then provides it for free so that ppl can download it and not pay the developers instead... 
Even ignoring copyright laws this is just absolutely not okey. This repo should be closed as its basically piracy with extra steps.

**Comment by Sarke** [comment]
It sounds like he has permission:

> Thanks to the team behind Jump King for letting me keep this up, u guys are legends

https://code-bullet.github.io/Jump-King/

**Comment by OneDeuxTriSeiGo** [comment]
> It sounds like he has permission:
> 
> > Thanks to the team behind Jump King for letting me keep this up, u guys are legends
> 
> https://code-bullet.github.io/Jump-King/

Ah I see that has been added. Thank you for pointing that out. As a result this issue is resolved and I'll close out this ticket.
