### ISSUE TITLE
How to run the genetic algorithm?

### ISSUE THREAD

**Issue by asok1** [Code-Bullet/Jump-King#5]
How do you run the machine learning algorithm locally? I got the app running and can play the game, but I'm not seeing how to run the autonomous agents.

**Comment by igorpwnd** [comment]
Well, first of all i suggest you to read the code as a way to understand the whole thing.
But if you want to jump straight to action.

Go to sketch.js, find the variable **testingSinglePlayer** and make it false.

Like this.
`let testingSinglePlayer = false;`
